---
title: "Intro to R for Researchers"
---

* [Workshop Slides]()
* Free Resources
    * R Programming
        * [Hands-on Programming with R](https://rstudio-education.github.io/hopr/) (for absolute beginners, i.e., if you have never programmed before)
        * [R for Data Science](https://r4ds.had.co.nz/) (learn how to manipulate, analyze and visualize data using R’s Tidyverse packages)
        * [Advanced R](https://adv-r.hadley.nz/) (if you plan to be really good at R)
        * [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/)
        * [The R Graph Gallery](https://www.r-graph-gallery.com/) (R graph samples with code)
        * [R Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/) (cheat sheets for many popular R packages)
        * [R for Stata Users](https://www.matthieugomez.com/statar/index.html) (if you are from the Stata world)
    
    * R for Empirical Research
        * [Introduction to Econometrics with R](https://www.econometrics-with-r.org/)
        * [Forecasting: Principles and Practice](https://otexts.com/fpp2/)
        * [Financial Engineering Analytics: A Practice Manual Using R](https://bookdown.org/wfoote01/faur/)
        * [Clustered and robust standard errors in Stata and R](https://rmcd1024.github.io/R_and_Stata/)
        
    * R and Machine Learning
        * [An Introduction to Statistical Learning / with Applications in R](http://faculty.marshall.usc.edu/gareth-james/ISL/index.html) (book and code)
        * [R interface to Keras](https://tensorflow.rstudio.com/keras/) (deep learning in R)
        
    * Plan to teach Econometrics using R?
        * [A Short R Tutorial](https://data.princeton.edu/R) by Germán Rodríguez (a good tutorial to get students started with R)
        * [Introductory Econometrics Examples](https://justinmshea.github.io/wooldridge/articles/Introductory-Econometrics-Examples.html) (data and examples from Wooldridge)


Back to [TDMDAL Computing Page](https://tdmdal.github.io/)